loadstring(game:HttpGet("https://raw.githubusercontent.com/cabscer/Yuno-Cheats/main/loader.lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/cabscer/Yuno-Cheats/main/loader.lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/cabscer/Yuno-Cheats/main/loader.lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/cabscer/Yuno-Cheats/main/loader.lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/cabscer/Yuno-Cheats/main/loader.lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/cabscer/Yuno-Cheats/main/loader.lua"))()
